import React, { useState } from 'react'
import { Badge } from "@/components/ui/badge"
import { Mail, Users } from "lucide-react"
import { Email, RoleEmail } from '../types'

interface EmailSeriesProps {
    emails: Email[]
    roleEmails: RoleEmail[]
    onEdit?: (content: string) => void
}

const EmailSeries = ({ roleEmails }: EmailSeriesProps) => {
    const [activeRole, setActiveRole] = useState<string>(roleEmails[0]?.role || '')

    if (!roleEmails || roleEmails.length === 0) {
        return (
            <div className="text-center py-12">
                <Mail className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-gray-900 mb-2">No Email Series Generated</h3>
                <p className="text-gray-600">Email content will appear here once generated by AI.</p>
            </div>
        )
    }

    return (
        <div className="space-y-4 sm:space-y-6">
            <div className="bg-gradient-to-r from-indigo-50 to-blue-50 p-4 sm:p-6 rounded-lg border border-indigo-200">
                <div className="flex items-center gap-3 mb-2">
                    <Users className="w-5 h-5 text-indigo-600 flex-shrink-0" />
                    <h3 className="text-base sm:text-lg font-semibold text-indigo-800">Role-Based Email Communications</h3>
                </div>
                <p className="text-indigo-700 text-sm sm:text-base leading-relaxed">
                    AI-generated email templates tailored for different stakeholder roles. Each email is customized
                    to address role-specific concerns and communication styles.
                </p>
            </div>

            {/* Sidebar Layout with Vertical Tabs - Responsive */}
            <div className="flex flex-col lg:flex-row gap-4 sm:gap-6 min-h-[400px] sm:min-h-[500px] lg:min-h-[600px]">
                {/* Left Sidebar - Role Tabs */}
                <div className="w-full lg:w-64 lg:flex-shrink-0">
                    <div className="bg-white border border-gray-200 rounded-lg overflow-hidden shadow-sm">
                        <div className="bg-gray-50 px-4 py-3 border-b border-gray-200">
                            <h4 className="font-semibold text-gray-900">Email Roles</h4>
                        </div>
                        {/* Mobile: Horizontal scrolling tabs */}
                        <div className="lg:divide-y lg:divide-gray-200">
                            <div className="flex lg:flex-col overflow-x-auto lg:overflow-x-visible scrollbar-hide">
                                {roleEmails.map((email) => (
                                    <button
                                        key={email.role}
                                        onClick={() => setActiveRole(email.role)}
                                        className={`cursor-pointer flex-shrink-0 lg:w-full px-4 py-4 text-left transition-colors hover:bg-gray-50 ${activeRole === email.role
                                            ? 'bg-indigo-50 border-b-4 lg:border-b-0 border-indigo-500 text-indigo-700'
                                            : 'text-gray-700 border-b-4 lg:border-b-0 border-transparent'
                                            } ${roleEmails.indexOf(email) !== roleEmails.length - 1 ? 'lg:border-b lg:border-gray-200' : ''}`}
                                    >
                                        <div className="flex items-center gap-2">
                                            <Mail className="w-4 h-4 shrink-0" />
                                            <span className="font-medium line-clamp-1">{email.role}</span>
                                        </div>
                                    </button>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Right Content Area - Email Details */}
                <div className="flex-1 w-full">
                    {roleEmails.find(email => email.role === activeRole) && (
                        <div className="bg-white border border-gray-200 rounded-lg shadow-sm">
                            {/* Header */}
                            <div className="bg-gradient-to-r from-indigo-600 to-indigo-700 text-white px-4 sm:px-6 py-4 rounded-t-lg">
                                <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-3 sm:gap-0">
                                    <div className="flex-1">
                                        <h3 className="text-lg sm:text-xl font-semibold flex items-center gap-3">
                                            <Mail className="w-5 h-5 sm:w-6 sm:h-6" />
                                            <span className="truncate">Email for {activeRole}</span>
                                        </h3>
                                        <p className="text-indigo-100 mt-1 text-sm sm:text-base">
                                            Targeted communication for {activeRole.toLowerCase()} stakeholders
                                        </p>
                                    </div>
                                    <Badge className="bg-white/20 text-white border-white/30 text-xs sm:text-sm px-2 sm:px-3 py-1 self-start">
                                        Ready
                                    </Badge>
                                </div>
                            </div>

                            {/* Content */}
                            <div className="p-4 sm:p-6 space-y-4 sm:space-y-6">
                                {/* Subject Section */}
                                <div>
                                    <label className="block text-sm font-semibold text-gray-700 mb-2 sm:mb-3">
                                        Subject
                                    </label>
                                    <div className="bg-gray-50 p-3 sm:p-4 rounded-lg border border-gray-200">
                                        <p className="text-gray-900 font-medium text-sm sm:text-base break-words">
                                            {roleEmails.find(email => email.role === activeRole)?.subject}
                                        </p>
                                    </div>
                                </div>

                                {/* Body Section */}
                                <div>
                                    <label className="block text-sm font-semibold text-gray-700 mb-2 sm:mb-3">
                                        Body:
                                    </label>
                                    <div className="bg-gray-50 p-3 sm:p-4 rounded-lg border border-gray-200 min-h-[250px] sm:min-h-[300px]">
                                        <div className="text-gray-700 leading-relaxed whitespace-pre-wrap text-sm sm:text-base break-words">
                                            {roleEmails.find(email => email.role === activeRole)?.body.replace(/\\n/g, '\n')}
                                        </div>
                                    </div>
                                </div>
                                
                                {/* Copyright Footer */}
                                <div className="pt-4 border-t border-gray-200">
                                    <p className="text-xs text-gray-500 text-center">
                                        (c)2025 Life Vision, LLC - Innovative Dialogs(R)
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    )
}

export default EmailSeries
