import React from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Video, Clock } from "lucide-react"

interface VideoScriptProps {
    videoScript: string | null
}

interface ParsedVideoScript {
    opening?: string
    supporting_visuals?: string
    executive_return?: string
    supporting_visuals_two?: string
    closing?: string
    fade_out?: string
}

const VideoScript = ({ videoScript }: VideoScriptProps) => {
    // Parse the JSON string
    const parsedContent: ParsedVideoScript = React.useMemo(() => {
        if (!videoScript) return {}
        try {
            return JSON.parse(videoScript)
        } catch (error) {
            console.error('Error parsing video script:', error)
            return {}
        }
    }, [videoScript])

    // Calculate total word count
    const calculateWordCount = () => {
        let totalWords = 0
        Object.values(parsedContent).forEach(section => {
            if (typeof section === 'string') {
                totalWords += section.split(' ').length
            }
        })
        return totalWords
    }

    // Calculate estimated duration (assuming ~150 words per minute)
    const calculateDuration = () => {
        const wordCount = calculateWordCount()
        const minutes = Math.ceil(wordCount / 150)
        return `${minutes} min`
    }

    if (!videoScript || Object.keys(parsedContent).length === 0) {
        return (
            <div className="text-center py-12">
                <Video className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-gray-900 mb-2">No Video Script Generated</h3>
                <p className="text-gray-600">Video script content will appear here once generated by AI.</p>
            </div>
        )
    }

    // Define sections in the specified sequence
    const sections = [
        { key: 'opening', label: 'Opening' },
        { key: 'supporting_visuals', label: 'Supporting Visuals' },
        { key: 'executive_return', label: 'Executive Return' },
        { key: 'supporting_visuals_two', label: 'Supporting Visuals 2' },
        { key: 'closing', label: 'Closing' },
        { key: 'fade_out', label: 'Fade Out' }
    ]

    // Combine all sections into a single formatted script
    const formatFullScript = () => {
        return sections
            .filter(({ key }) => parsedContent[key as keyof ParsedVideoScript])
            .map(({ key, label }) => {
                const content = parsedContent[key as keyof ParsedVideoScript]
                if (!content) return null
                
                // Clean and format the content
                const cleanContent = content
                    .replace(/\\n/g, '\n')  // Convert escaped newlines
                    .replace(/&amp;/g, '&')  // Convert HTML entities
                    .replace(/\s+—\s+/g, ' — ')  // Fix em dash spacing
                    .trim()

                // Process content to convert bracketed text to headings
                const processedContent = cleanContent.replace(
                    /\[([^\]]+)\](\s*)/g, 
                    '<h4 class="font-semibold text-gray-800 mb-2 mt-4">$1</h4>'
                )

                return (
                    <div key={key} className="mb-8">
                        <h3 className="text-lg font-bold text-gray-900 mb-4 uppercase tracking-wide">
                            {label}
                        </h3>
                        <div 
                            className="text-sm text-gray-700 leading-relaxed whitespace-pre-line"
                            dangerouslySetInnerHTML={{
                                __html: processedContent
                            }}
                        />
                    </div>
                )
            })
    }

    return (
        <Card className="border-0 shadow-sm bg-white">
            <CardHeader className="bg-gradient-to-r from-indigo-600 to-indigo-700 text-white rounded-t-lg">
                <div className="flex justify-between items-start">
                    <div>
                        <CardTitle className="flex items-center gap-3 text-xl">
                            <Video className="w-6 h-6" />
                            Change Management Video Script
                        </CardTitle>
                        <CardDescription className="text-indigo-100 mt-2 flex items-center gap-4">
                            <span className="flex items-center gap-2">
                                <Clock className="w-4 h-4" />
                                Duration: {calculateDuration()}
                            </span>
                            <span>{calculateWordCount()} words</span>
                            <span>{sections.filter(s => parsedContent[s.key as keyof ParsedVideoScript]).length} sections</span>
                        </CardDescription>
                    </div>
                    <Badge className="bg-white/20 text-white border-white/30">Ready</Badge>
                </div>
            </CardHeader>
            <CardContent className="p-6">
                <div className="bg-gray-50 p-6 rounded-lg border">
                    {formatFullScript()}
                </div>
            </CardContent>
        </Card>
    )
}

export default VideoScript
